---
title: "plot data analysis"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup, include=FALSE}

library(dplyr)
library(tidyr)
library(ggplot2)
library(xtable)
library(gsubfn)
library(fmtr)

library(ggthemes)
theme_set(theme_light())
'%!in%' <- function(x,y)!('%in%'(x,y))
options(scipen = 999)
options(digits = 4, nsmall = 3)

```

#roundingSat
```{R}
t <- data.frame()
rs <- read.csv("roundingSat.csv", header = TRUE)

solvedIns <- rs %>% filter(sol!='timeout') %>% summarise(solvedIns = n())
solveTime <- rs %>% filter(sol!='timeout') %>% summarise(solveTime=mean(rsTime))
preTime <- data.frame(NA)
decfasterNum <- data.frame(NA)
decfasterMean<- data.frame(NA)
decfasterMedian<- data.frame(NA)
decslowerNum<- data.frame(NA)
decslowerMean<- data.frame(NA)
decslowerMedian<- data.frame(NA)
nCall<- data.frame(NA)
nApplied<- data.frame(NA)
red<- data.frame(NA)

rsTable <- data.frame(row.names = 'roundingSat')

rsTable <- bind_cols(
    solvedIns,
    solveTime,
    preTime,
    decfasterNum,
    decfasterMean,
    decfasterMedian,
    decslowerNum,
    decslowerMean,
    decslowerMedian,
    nCall,
    nApplied,
    red
)
rsTable <- rsTable %>% setNames(nm = c('solvedIns','solveTime','preTime','decfasterNum','up mean(%)', 'up median(%)','decslowerNum','down mean(%)','down median(%)','nCall','nApplied(%)','red%'))
rownames(rsTable)<-c('roundingSat')

t <- t %>% bind_rows(rsTable)
t
```

# helper functions
```{r}
analysis <- function(a,b,name,redType){
  
  paramB <- b %>% filter(status=='*') %>% setNames(nm = c("status", "file", "ncalls", "succe", "tsx", "tsxapp", "time", "variables", "constraints"))
  print(paramB)
  
  appliedB <- paramB %>% filter(as.double(tsxapp)!=0) %>% pull(file)
  
  b <- b %>% filter(status=='$')
  timeoutA <- a %>% filter(sol=='timeout')
  timeoutB <- b %>% filter(sol=='timeout')
  solvedA <- a %>% filter(sol!='timeout')
  solvedB <- b %>% filter(sol!='timeout')
  commonFile <- intersect(solvedA %>% pull(file), solvedB %>% pull(file))
  bothSolvedA <- solvedA %>% filter(file%in%commonFile & file%in%appliedB) # where tech applied
  bothSolvedB <- solvedB %>% filter(file%in%commonFile & file%in%appliedB) # where tech applied
  extraSlower <- solvedA %>% filter(file%!in%solvedB$file)
  extraFaster <- solvedB %>% filter(file%!in%solvedA$file)
  speedTable <- bind_rows(bothSolvedA, bothSolvedB) %>%
    group_by(file) %>%
    arrange(desc(status), by_group = TRUE) %>%
    summarise(
      diff = as.double(first(rsTime) - last(rsTime)), # diff>0 faster
      diffRatio = 100 * abs(as.double(first(rsTime) - last(rsTime))) / as.double(first(rsTime))
    )
  # print(bothSolvedA)
  # print(bothSolvedB)
  # print(solvedB)
  # print(speedTable %>% filter(diff<0))
  print(extraFaster)
  
  #correct
  correct_ans <-
    all(bothSolvedA %>% pull(sol) == bothSolvedB %>% pull(sol)) &&
      all(bothSolvedA %>% filter(sol == "1") %>% pull(obj)
      == bothSolvedB %>% filter(sol == "1") %>% pull(obj))
  #time
  solvedIns<- solvedB %>% summarise(solvedIns=n())
  solveTime<- solvedB %>% summarise(solveTime=mean(as.double(rsTime)))
  preTime<- solvedB %>% summarise(preTime=mean(as.double(preTime)))
  
  #faster
  decfasterNum<- speedTable %>% filter(diff>0.0) %>%summarise(decfasterNum = n()+nrow(extraFaster))
  decfasterMean<- speedTable %>% filter(diff>0.0) %>%summarise('up mean(%)'=mean(diffRatio))
  decfasterMedian<- speedTable %>% filter(diff>0.0) %>%summarise('up median(%)'=median(diffRatio))
  
  #slower
  decslowerNum<- speedTable %>% filter(diff<0.0) %>%summarise(decslowerNum = n()+nrow(extraSlower))
  decslowerMean<- speedTable %>% filter(diff<0.0) %>%summarise('down mean(%)'=mean(diffRatio))
  decslowerMedian<- speedTable %>% filter(diff<0.0) %>%summarise('down median(%)'=median(diffRatio))
  
  #param
  nCall<- paramB %>% filter(ncalls!=0) %>% summarise(nCall=mean(as.double(ncalls))) 
  nApplied <- paramB %>% filter(ncalls!=0) %>%summarise('nApplied(%)'=100*sum(tsx!=0)/n())
  nred <- paramB %>% filter(tsx != 0) %>% mutate(red = (tsx * tsxapp / 100) / variables) %>% summarise("red%" = mean(red) * 100)
  mred <- paramB %>% filter(tsx != 0) %>% mutate(red = (tsx * tsxapp / 100) / constraints) %>% summarise("red%" = mean(red) * 100)

  #summarise
  table <- data.frame(row.names = name)
  table <- table %>% bind_cols(
    solvedIns,
    solveTime,
    preTime,
    decfasterNum,
    decfasterMean,
    decfasterMedian,
    decslowerNum,
    decslowerMean,
    decslowerMedian,
    nCall,
    nApplied,
    if(!redType){nred}else{mred}
  )
  table
}
```

#all
```{R}
all <- read.csv("all.csv", header = TRUE)
all <- all %>% filter(abs(totTime)>1e-7)
res <- analysis(rs,all,'all',1)
t<- t %>% bind_rows(res)
t
```

#Cummulative Plot
```{r}
rs$status<-'roundingSat'
decA<-rs %>% filter(file%in%decfile$file)
decB<-PureLit %>% filter(file%in%decfile$file & status!='*')
decB$status<-'purelit'
dec<-bind_rows(decA,decB) %>% cbind(family='dec')
optA<-rs %>% filter(file%in%optfile$file)
optB<-PureLit %>% filter(file%in%optfile$file & status!='*')
optB$status<-'purelit'
opt<-bind_rows(optA,optB) %>% cbind(family='opt')

#opt$rsTime[abs(opt$rsTime-0.0)<1e-6]<-0.00001
data<-bind_rows(dec,opt)
data$rsTime[abs(data$rsTime-0.0)<1e-6]<-1e-2 # set papilo already solved instances to 0.00001

df <- data %>% 
  filter(sol!='timeout') %>%
  arrange(status, rsTime) %>% 
  group_by(status) %>% 
  mutate(nsolved=rank(rsTime))  %>%
  select(status, rsTime, nsolved)


ggplot(df, aes(x = rsTime, y = nsolved, color = status, shape = status)) +
  geom_point() +
  geom_line() + 
  scale_x_log10()
```
# Scatter Plot

```{r}
timeout <- 5000

data

df <- data %>%
  mutate(time=ifelse(sol=='timeout',2*timeout, rsTime)) %>%
  select(family,file,status,time) %>%
  pivot_wider(names_from = status, values_from = time)

faster<-df %>% mutate(diff=rs-purelit) %>% filter(diff>0) 
slower<-df %>% mutate(diff=rs-purelit) %>% filter(diff<0) 
faster
slower

ggplot(df, aes(x = rs, y = purelit, color = family)) +
  geom_point() +
        scale_x_log10() +
        scale_y_log10() +
        coord_fixed(ratio = 1) +
        geom_vline(xintercept = timeout, linetype="dashed") +
        geom_hline(yintercept = timeout, linetype="dashed") +
        geom_abline(slope = 1, intercept = 0, linetype="dashed")
```


#Scaling Plot

```{r}
ggplot(
  data %>% filter(family == "benchmarkC", solver == "SolverA"),
  aes(x = scaling, y = time, color = solver)
) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm")

lm(log10(time) ~ log10(scaling), data = data %>%
  filter(family == "benchmarkB", solver == "SolverB1"))
```



# Labels and Captions

```{r}
timeout <- 5000

df <- data %>%
  mutate(time = ifelse(status == "timeout", 2 * timeout, time)) %>%
  select(family, instance, solver, time) %>%
  pivot_wider(names_from = solver, values_from = time)

# let us also use shapes this time
ggplot(df, aes(x = SolverA, y = SolverB2, color = family, shape = family)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  coord_fixed(ratio = 1) +
  geom_vline(xintercept = timeout, linetype = "dashed") +
  geom_hline(yintercept = timeout, linetype = "dashed") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  ylab("SolverB2 (time in s)") +
  xlab("SolverA (time in s)") +
  # Note that we need to redefine the label for color AND shape
  labs(color = "Benchmark Family", shape = "Benchmark Family", title = "A fancy plot")
```


#Boxplot

```{r}
df <- data %>%
  select(family, instance, solver, time) %>%
  pivot_wider(names_from = solver, values_from = time) %>%
  mutate(speedup = SolverB1 / SolverB2)

ggplot(df, aes(x = family, y = speedup)) +
  scale_y_log10() +
  geom_boxplot()
```